name: Release
on: 
  workflow_dispatch:

jobs:
  update-release-branch:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/releases/') }}
    steps:
    - id: version
      name: Infer version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/releases/}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TAG_PSAT }}
    - run: echo ${{ steps.version.outputs.version }}
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        tag: 'v${{ steps.version.outputs.version }}'
