name: Trigger Vanity imports generation 

on:
  repository_dispatch:

jobs:
 RepoAjobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: revit13/vanity-imports
          event-type: vanity-import-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

